site_name: Docs as Code Project
docs_dir: docs

nav:
  - HomePage Test: index.md
  - Glossary: glossary.md
  - Test Page: testpage.md

  - Overview:
      - FAQ: FAQ.md
      - Glossary: Glossary.md
      - Guideline to Documentation Changes: Guideline-to-documentation-changes.md

  - CreateApplicationProcess:
      - SendApplication:
          - General: CreateApplicationProcess/SendApplication-General.md
          - Use Cases: CreateApplicationProcess/SendApplication-UseCases.md
          - Schemas: CreateApplicationProcess/SendApplication-Schemas.md
          - Data Model: CreateApplicationProcess/SendApplication-DataModel.md

      - ApplicationEntityCreation:
          - General: CreateApplicationProcess/ApplicationEntityCreation-General.md
          - Use Cases: CreateApplicationProcess/ApplicationEntityCreation-UseCases.md
          - Schemas: CreateApplicationProcess/ApplicationEntityCreation-Schemas.md
          - Data Model: CreateApplicationProcess/ApplicationEntityCreation-DataModel.md

  - Risk-CheckProcess:
      - Stages DM1â€“DM7: Risk-CheckProcess/Stages-DM1-DM7.md

  - DecisionProcess:
      - SendingStatus:
          - General: DecisionProcess/SendingStatus-General.md
          - Use Cases: DecisionProcess/SendingStatus-UseCases.md
          - Schemas: DecisionProcess/SendingStatus-Schemas.md
          - Data Model: DecisionProcess/SendingStatus-DataModel.md

      - ReceivingADecision:
          - General: DecisionProcess/ReceivingADecision-General.md
          - Use Cases: DecisionProcess/ReceivingADecision-UseCases.md
          - Schemas: DecisionProcess/ReceivingADecision-Schemas.md
          - Data Model: DecisionProcess/ReceivingADecision-DataModel.md

      - DecisionToCreditFactory:
          - General: DecisionProcess/DecisionToCreditF
- OpenAPIServies: Services.md
